### ISSUE TITLE
Raiders can still get stuck when enclosed in a big area

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#263] opened 2016-06-12 21:03 UTC
When in Auto-Raid mode, it seems raiders can still spawn inside enclosed areas:

![image](https://cloud.githubusercontent.com/assets/4981659/15993807/edf97890-30f1-11e6-84dd-1ab76fb8275d.png)

**Comment by askebv** [comment] 2016-06-14 05:51
It doesn't seem to happen in auto-increase mode however. At least not after 12+ hours of running it for me.

**Comment by DaemoniaV** [comment] 2016-06-16 07:07
My War morning hide somewhere too. Click by portrait show this picture.
![bug6](https://cloud.githubusercontent.com/assets/19784493/16108144/10f530b8-33aa-11e6-9392-0d69cc65bc0c.jpg)

**Comment by askebv** [comment] 2016-06-16 07:11
You can find them by using the equipment and statistics window.

**Comment by TravisGesslein** [comment] 2016-06-17 18:43
Very strange... can't reproduce for now. Any idea when this happens specifically? Did the raider just die?

**Comment by askebv** [comment] 2016-06-17 18:45
Not entirely sure. But it always happens before starting the next raid. And I've only seen it in auto-raid mode.

**Comment by askebv** [comment] 2016-06-18 11:32
@Heishe I just had it happen again. I had the game running in low-power-mode - with auto-raid mode active - for over an hour.
It's the third time I notice that it happened while waiting for the Chamber of the Sealer raid. I don't know if that's related though, but here's a few screenshots:

![image](https://cloud.githubusercontent.com/assets/4981659/16170606/b33e5caa-3558-11e6-821e-05f37c038b90.png)

![image](https://cloud.githubusercontent.com/assets/4981659/16170610/c0c65a58-3558-11e6-9638-361210a32999.png)

Just as I returned to the game, I heard a simultaneous sound playback of the command skill and a basic attack, and saw a lot of items funnel into the inventory.

Note also, that activating sleep mode makes the raider teleport out of the area.

**Comment by askebv** [comment] 2016-06-18 11:53
I don't think it's related to dying, since I just had it happen in Gardens of Eternity, with level 54 raiders, with this gear:

![image](https://cloud.githubusercontent.com/assets/4981659/16170677/f3409f7c-355b-11e6-9c3b-97d76a85ebf2.png)

**Comment by askebv** [comment] 2016-06-19 10:20
@Heishe Now I've had it happen twice in a row. After it happened, I put my raiders to sleep mode and launched auto-raid mode again, and it still didn't work. To me it seems it could be related to being in raid view when raiders are teleported back to the base. Because when I put it into sleep mode and view the base, I never have problems.

**Comment by TravisGesslein** [comment] 2018-02-06 12:47
After investigating the code, this shouldn't happen anymore, or rather, if it does, it will be an error with the physics system / movement code, for which various other open issues exist. Closing this for now.

**Closed as completed by TravisGesslein** 2018-02-06 12:47 UTC
