### ISSUE TITLE
Enemy health bar outside screen.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#61] opened 2016-06-02 20:02 UTC
http://imgur.com/1w7pJa2

The first enemy hp bar was not visible at all. In single target bosses i couldn't see their health! I tried the reset window but didn't work. Got fixed by refreshing the page.

**Comment by askebv** [comment] 2016-06-03 11:11
I just had this occur to me too:

![image](https://cloud.githubusercontent.com/assets/4981659/15777017/72be5716-298c-11e6-8bbf-23be4ccbbf21.png)

I'm thinking it could be related to the fact that I killed 1 or 2 of the parts (dogs) of the boss while having the health bars shown, and then died before clearing them all.

And then this bug happened after relaunching the raid.

Does that sound right for you too, @Ethismos ?

**Comment by TravisGesslein** [comment] 2016-06-03 23:21
Having a hard time reproducing this.

**Comment by askebv** [comment] 2016-06-04 07:09
I can clarify what I think I did - which could be hard to reproduce without some debug monitoring tools.

Anyway:
1. Launch the 4th raid.
2. Clear everything up to the 4th boss encounter.
3. Open the health bars of the 4th boss.
4. (Maybe) view the base as the encounter continues
5. Kill only some of the bosses (maybe it's specific ones)
6. Die before killing off more.
7. Relaunch the raid

Alternatively, you can try being in build mode in step 4 as well. Another thing I might have done differently, was viewing the health bars of one of the prior dead bosses in step 3.
It could also be something to do with the low-performance-out-of-focus mode.

Anyway, I'm just shooting in the dark here, but that's just about how I recall it happening. I know I was AFK during the 4th boss encounter, so I sadly didn't see exactly what happened.

**Comment by TravisGesslein** [comment] 2016-06-04 10:48
Whew... tried a lot and can't reproduce. Obviously it's real so I put in some blind safeguards by resetting the positions of those character views to their proper positions whenever I can. I'll leave this open in case the error pops up again after Beta Patch 3.

**Comment by TravisGesslein** [comment] 2016-06-12 02:24
Nobody encountered this anymore right? Closing it for now then.

**Closed as completed by TravisGesslein** 2016-06-12 02:24 UTC
Labels: game bug
