### ISSUE TITLE
BUG: Second page of  inventory dissapear((((

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#314] opened 2016-07-18 19:14 UTC
![bug01](https://cloud.githubusercontent.com/assets/19784493/16927208/fba84138-4d34-11e6-82e2-fcbcd5580ca4.jpg)

**Comment by DaemoniaV** [comment] 2016-07-18 19:37
After some new item drop and buy of Metals second page coming up.

**Comment by TravisGesslein** [comment] 2016-07-18 19:55
Weird... how many items did you have on the second page?

**Comment by DaemoniaV** [comment] 2016-07-18 20:19
When I noticed that it appear again it was 5 on it.

**Comment by Talisca** [comment] 2016-07-19 10:12
There happens to be some kind of inconsistency in the check for the tabs.

@DaemoniaV are you sure you had more than 96 different items (one full page?). If so, I am not able to reproduce this behavior :(

**Comment by DaemoniaV** [comment] 2016-07-19 11:08
Sure. Many weeks I check 2 page and there is 4 items. One lucky dayIfound a 5 items there - there is Old Cane add at 1page) Can send You Mysave that was with 5 items and when loaded there is 2 page missing. Seems the some items not only not showed but full dissapeared.

**Comment by TravisGesslein** [comment] 2017-02-06 12:07
This should be fixed in current version.

**Closed as completed by TravisGesslein** 2017-02-06 12:07 UTC
