### ISSUE TITLE
Can't play (All saved games all browsers bugged)

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#94] opened 2016-06-03 16:26 UTC
http://imgur.com/LgfpXaY

Happens with all my save games from the oldest to newest and when i try to start new game from scratch. Any chance you are patching something?

**Comment by Drakenfeld** [comment] 2016-06-03 16:28
After you import the game refresh the game and it should load, i had the same problem when i changed computers.

**Comment by Ethismos** [comment] 2016-06-03 16:33
Nope, and i have the same issue with ALL save games (from the first export i did tll now) at ALL browsers (opera, firefox, chrome).

Time to watch some lcs !

**Comment by TravisGesslein** [comment] 2016-06-03 16:49
Not patching at the moment. That's not good. Could you send me the savegame? social at pitforest de or travis.gesslein at pitforest de.

**Comment by TravisGesslein** [comment] 2016-06-03 16:50
Wait a sec... when you are starting a new game too? That's pretty WTF

**Comment by TravisGesslein** [comment] 2016-06-03 16:53
That message is shown whenever anything in the game's loading procedure crashes. I have no concrete ideas but this could be an issue with our server as opposed to the game itself. Could also be an issue with your local machine but since it worked fine before that's unlikely, unless you installed browser related stuff recently.

Could you make a screenshot of the errors the console is showing when that happens? F12 on most browsers. Chrome will show you red errors which have little red arrows to click to expand them. Would be good if you could expand some of them and make a screenshot. Much appreciated.

**Comment by Ethismos** [comment] 2016-06-03 16:59
So, i just send 2 save games with about 15 minutes difference that are both bugged. If i use any of them i can't start a new game or load any other save file until i close the broswer and go back in, in which case i can start a new game.

 I only had 2 games at cloud so i may have to start over unless i got a save from before my first reset.

I will try to check for errors and post them here.

**Comment by TravisGesslein** [comment] 2016-06-03 17:04
Ah good, it crashes for me too. I'll try to fix it asap.

**Comment by Ethismos** [comment] 2016-06-03 17:10
http://imgur.com/R36cUNk

I think it is not the mixed content stuff because i get it at every browser while i 'm at the starting menu and it doesn't keep updating after i choose a save game, wether its a bugged or normal/new one.

Probably the source error thing :)

**Comment by TravisGesslein** [comment] 2016-06-03 17:17
I analyzed it and I think this will require a code fix. We'll try to fix it and upload Patch 2 as soon as possible (smaller patch this time, just getting started with work for the most part) which should fix this.

**Comment by Ethismos** [comment] 2016-06-03 17:19
Ok, guess i ll take a break for a few hours !

**Comment by TravisGesslein** [comment] 2016-06-03 18:17
Okay, this had something to do with skill priority lists. In your savegame the game basically thinks that an entity has more skills than it really has, probably because somethign went wrong when you changed the skill priority list of one of the raiders. 

We haven't fixed the root problem of why this happens, but we implemented a fix that simply restores the skill priority list to its default order when it loads the savegame and detects that something's wrong. Our hope is that if people start noticing that their skill priority lists are constantly being reset to default, we will track down some way to reproduce the issue (because whenever that happens, that player must have done something before reloading the game which triggered the fault). Will be uploaded soon.

**Comment by TravisGesslein** [comment] 2016-06-03 18:18
I'm closing this issue but will a new one that better fits the description of the actual problem.

**Closed as completed by TravisGesslein** 2016-06-03 18:18 UTC
Labels: game bug
