### ISSUE TITLE
Some crazy suggestion...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#210] opened 2016-06-08 21:44 UTC
It is dark and cold snowy night on other side of my window. Bears with balalaika scour al around. And My head full of thoughts...
1) Thank You for great game. It is some years ago I have so much fun from game.
2) I think the main source of pleasure is fell of progress. First I "meet wall" on 50 level "cap". Then begin farmig Raid and slow - one by one progress. I remember how boss from R5 survive with ONE hp and how incredible turn of critical hits give me chance to wipe R4 final monster. This is cool but always wish more...
So it is dream about bit more strategical game. In today reality I open R6 just two switches in my strategy - add Calming Shot for R4 Dog and some Challenging Cry for minions of R5. May be every boss need to rebuild the strategy. Let it option to create auto-use snapshotes for every Raid part. When raiders begin R4 they auto use snapshot saved as BeginR4. After killing first group they auto use snapshot SecondBossR4. So You quest is not simple farm previous monsters.
3) As End Game content there is several Uber-Bosses. To meet them you need do some crazy stuff quest. Example - Uber Count Slime. Q1 - Need to kill 100.000 slimes in 24h, Q2 - Have 10 slimes Charmed one time on any map, Q3 - Kill 10 slimes in a Row with no damage taken.
The open portal for Uber Boss. But there is only beginning.. He just jump and oneshot all party single hit. But now you get Old Slime Hunter Manuscript. There is list of some (not exactly named) location where You can farm Old Hunter Set Items. "In area with great lake you found slimy hat", "The pretty weasels bring You to "Slug armor". When you cllect all set final set bonus - "Decrease damage from Count Slime by 100" so now he weaker in 100 times and have some chance. This is give to players reason to back on old farm location and raids.
4) Some not standart mechanics -
a) Let boss steal part of You equipment when You fight. Bring back auto after end fight of only if You win.
b) Boss change sources of raiders - Mages cast by using Rage from Warriors.
c) Boss oneshop with scream "Even!" - it is happen only if You have even level.
d) Boss damage is you gold amount)
I am finish... Bears scratches in My window need to throw them some Vodka...
p.s. With regards from Cold Mother Russia

**Comment by TravisGesslein** [comment] 2016-06-09 10:25
Do they look like this? ![bear_plays_balalaika](https://cloud.githubusercontent.com/assets/2046189/15926166/bf7193ae-2e3a-11e6-84cc-5d16104b2fd1.jpg)

It's not a bear... it is someone who wants free vodka in disguise.

Anyways thank you for the suggestions. I love the idea of very hard (optional) end game content, but we are still unsure of how to implement it properly. 

Because the problem is that our "end-game" will move along every time we release new raids with better equipment and other content, which is supposed to happen pretty regularly. So if we implement this content now and balance it in accordance to whatever the last raid will be in re-release, it will become too easy once we release raids after that... any ideas anyone?

I also agree about the thing with the feeling of raid progression. That "slow and painful" step by step feeling of inching slightly further into a raid is the core feeling is the reason I started prototyping this game in the first place. The re-release probably doesn't nail it completely right now, because it's a bit too easy. We will do a better balancing job with future raids.

With boss design in particular I agree that it is cool if the boss requires alternative strategies and experimentation to beat. All of the bosses in R4 were designed with this in mind. All of them have some mechanic where it is supposed to be a major benefit to have a certain "counter" active (although it's possible that this is designed too weakly atm). 

But I never want to go "full retard" with this and require a highly specific build or something to beat a boss (although this is an option for optional bosses and raids and stuff) because this game is also a lot about giving players options for building something that they like (instead of forcing you to build towards something that is optimal for a certain boss or whatever, although that is fine too of course if that's what you're into). 

In the end I think we can hit a balance where we design bosses such that players with optimal strategies can find very fast routes through the game while people who just want to kind of play along and experience the game at their own pace can still get that same feeling of "hard earned progression".

Oh and regarding the specific suggestions, I will note down "Old Slime Hunter" on our internal to do lists, sounds like a good idea to do something with this :hankey:

**Comment by DaemoniaV** [comment] 2016-06-09 10:34
Thx for answer.
Bears more like this...
https://i.ytimg.com/vi/9fHYXVFOusU/hqdefault.jpg

**Closed as completed** 2016-06-09 11:46 UTC
Labels: feature suggestion
