### ISSUE TITLE
Disabling effects when window is not open makes there be a bunch of effects when you go back to the window

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#133] opened 2016-06-05 09:21 UTC
Coins and marked targets at least all accumulate and play together later when you come back to the window with effects disabled

![image](https://cloud.githubusercontent.com/assets/11687574/15804618/26ff9cac-2ac4-11e6-85f8-c189af52a0bc.png)

**Comment by TravisGesslein** [comment] 2016-06-05 12:24
I think we just forgot to disable some of them when the flag is activated. This leads to them getting queued up when you're tabbed out of focus.

**Comment by TravisGesslein** [comment] 2016-06-05 12:28
Actually... checking the code they are definitely disabled correctly. Might be a bug with the options menu instead... maybe it doesn't correctly update the settings you choose in the options menu.

**Comment by TravisGesslein** [comment] 2016-06-05 12:30
Can you check if the option is actually still enabled for you?

**Comment by TravisGesslein** [comment] 2016-06-05 12:33
Also! It might be an issue with how we detect whether or not a window is focused. Could you tell us what exactly you do to make the window not have focus? Just activate a different tab? Minimize the window? (by clicking on the minimize button, or some key combations, etc?). Also which browser do you use?

**Comment by thorbrian** [comment] 2016-06-05 18:53
Hmm... checkbox is off now - and it seems to be staying on when I click it on now

so I guess it's queueing up effects when effects are on (so when checkbox is off)

browser is chrome, I'm just switching between tabs

**Comment by TravisGesslein** [comment] 2016-06-12 08:29
Yup, that's one of the reasons the setting is there. So I'll close this for now because it's more or less working as intended. The issue is not nice of course but there's not much we can do about it right now

**Closed as completed by TravisGesslein** 2016-06-12 08:29 UTC
Labels: game bug
