### ISSUE TITLE
Arena difficulty

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#169] opened 2016-06-06 19:32 UTC
First wave of arena (a skeleton boss) one shots my level 56 main tank with 3308 health and 65% damage taken, is the difficulty broken, or are we supposed to not do arena until more content is released?

**Comment by askebv** [comment] 2016-06-06 20:43
How do you access the arena? :blush:

**Comment by Ethismos** [comment] 2016-06-06 20:45
Click the cave at base and pay 1500 ^^

**Comment by askebv** [comment] 2016-06-06 20:46
Ah right - so it's basically just a random raid boss in arena? Not the old kind of arena?

**Comment by Ethismos** [comment] 2016-06-06 20:48
Seems like it, but i get one shotted, i guess i need to get some very high level to test that for bugs.

**Comment by askebv** [comment] 2016-06-06 21:01
I got curious and tested it out myself. I'm level 57, and close to what you have, my main tank has 3308 health with 67% damage taken. I also met the skeleton boss which one shot him - and obviously the others too. Stay At Range didn't do much either. I think I got him down to about 95% hp, but it's hard to tell.

Definitely some :fish:y balance there

**Comment by Ethismos** [comment] 2016-06-06 21:07
Well, checking the code there are quite a few things with 10k+ damage per hit, so i suppose they are intended for later stages of the game...

I will try to get some insane level for test purposes and fight this skeleton guy though.. its personal now.

**Comment by askebv** [comment] 2016-06-06 21:12
Either way, it's definitely not very user-friendly not to hint this. It's a lot of money to spend on something you can't possibly win at this time. If it is intended to be this way, then I think the availability of the building plans for this mystery cave should require something that aligned with being able to kill the first boss in the arena pretty soon thereafter. E.g. having beaten the 15th raid. Having 10/10 in reduced boss HP. Having earned at least 100,000 ancient artifacts. etc. etc.

**Comment by thorbrian** [comment] 2016-06-07 04:27
Yeah, I'm pretty motivated to try and beat him too :)

**Comment by Ethismos** [comment] 2016-06-07 07:55
Spoiler:

Killing the first boss gives the insane amount of 16(!) gold from the chest!

In one hour i will know if there is a second boss or not.

**Comment by askebv** [comment] 2016-06-07 08:48
Come on, that's just OP! The return of investment is almost unfathomable. 

So does he drop the usual leather and sword? Or just nothing?

**Comment by Ethismos** [comment] 2016-06-07 09:21
Both times no drops, just the arena chest giving 16 gold. Also no second "wave" or boss.

**Comment by TravisGesslein** [comment] 2016-06-07 13:35
The arena boss scaling isn't working as intended, but the fix won't make it into Beta Patch 4 (which we'll upload pretty soon). They're supposed to be about as difficulty as the first boss of the latest raid you're attempting.

The new arena is supposed to give players another chance at additional item drops from the same boss, either in order to progress a little faster in return for some gold, or just to get additional drop chances at very rare drops. 

Also, by default there should only be 1 boss wave but there will be an Ancient Wisdom upgrade to increase the wave count.

**Comment by TravisGesslein** [comment] 2017-02-05 18:15
Closing this now as Arena is removed until we can do something proper with the feature.

**Closed as completed by TravisGesslein** 2017-02-05 18:15 UTC
