### ISSUE TITLE
Saving Throw is only used when the warrior has no targets

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#104] opened 2016-06-03 21:01 UTC
When the warriors are currently occupied, they don't seem to use Saving Throw:

![image](https://i.gyazo.com/7770c065499623918600c5370c22b7ef.gif)

Is that intended? If so, then I hardly see any use. I thought it was supposed to help me clear the 5th raid. But apparently I have to get lucky with Scholar RNG and get Challenging Cry sometime?

I know the skill has a 20 second cooldown, but even when I observe the screen actively for several minutes, I don't usually see it. I've only seen it happen twice since I got it 2 hours ago. And both those times were a warrior that had just killed their own target, and then coming to aid the other raiders.

**Comment by Drakenfeld** [comment] 2016-06-03 21:44
Must have an poor setup or bad luck with gear, I beat the 7th raid last night, Try using magic missile + 2 arcane bombardment + arcane barrage and equip max mana items. 7 attacks at x2 damage each hit for 40Mp at time, with enough mp you can wipe any boss.

**Comment by askebv** [comment] 2016-06-03 21:46
I don't have arcane bombardment, whatever that is. I only have barrage and frenzy. It also sounds kinda buggy that you can wipe a boss just with 280 mp. I'm getting nowhere near that. At level 52 I could only get the 5th raid boss down to around 3k hp, if I got lucky with the fire elementals not killing/attacking the wrong people.

**Comment by Drakenfeld** [comment] 2016-06-03 21:49
really bad luck then... got 3 so far from the book npc. wish that npc updated more often and gave more books at a time. RNG much! 
![raiders7](https://cloud.githubusercontent.com/assets/19689960/15793660/6bf47842-29dd-11e6-9e31-85f48bd4b786.png)

**Comment by askebv** [comment] 2016-06-03 21:51
I guess. Instead I got 3 Shield blocks and 3 Bulwarks! :P

Btw 2 additional magic missiles would be x1.67 damage, since magic missiles fires 3 missiles by default. But that is still pretty overpowered, I'd say.

I don't think we're supposed to finish the raids as fast as you have, just by getting lucky with mage skillbooks.

**Comment by Drakenfeld** [comment] 2016-06-03 21:57
well 7 magic missiles overall at x2 damage each would be x14 or x2 of basic fireball per cast with none stop casting, + mana potions for the harder bosses. now at 445 Mp on that Mage, maybe i shouldn't of said anything because it is extremely op build.

**Comment by askebv** [comment] 2016-06-03 22:00
I've only gotten 2 mana potions in all my playtime (with the game open pretty much 24/7). So your strategy also depends on your RNG in the market :stuck_out_tongue: 

Also, I think you've misunderstood the purpose of this closed beta. We're supposed to _EXPOSE_ the glitches so they can improve the game, not keep them to ourselves so we can abuse them :laughing:

**Comment by Drakenfeld** [comment] 2016-06-03 22:03
bu bu buttt! I love the build to much to give it up hahaha! /delete post so noone else sees it mahaha! nah i don't mind we sort of need more unique builds in this game or everyone will just have the same setups.

**Comment by Ethismos** [comment] 2016-06-03 23:24
I also found similar builds to be kind of OP as i said at another thread, but it is really luck dependant.. will you get decent books? If yes, op mage. If not, to bad and cry...

I would say that builds work in different ways: fire = big crits, i like them while farming to one shot minions (especially healers), frost = fastest cast, good procs (buffs/debuffs) with fast cast speed, arcane = consistent good damage. They could use some balance tbh (frost bonus dps books give 15% dps average and a 10% atk speed debuff for 10 sec, arcane gives 40% damage, gets OP quickly), but i like the idea of different builds for different reasons.

**Comment by TravisGesslein** [comment] 2016-06-07 09:41
Magic missiles mage was supposed to be a "insane damage but high mana cost" build, since it focuses on attack/casting speed (there's also a skillbook that reduces the cooldown of the skill to 0). I will probably adjust the build at that end as opposed to nerfing the damage.

**Comment by TravisGesslein** [comment] 2016-06-07 09:45
Also... it's possible none of you have found them yet, but there are higher level skillbooks of the same skills. In particular there's a Level 2 Fireball and Level 2 Frost Shard skillbook. We figured that if we keep dropping higher level versions of the same skill, we encourage players to play around with different builds once they get lucky and get a rare higher level version of a certain skill (e.g. Fireball lvl 2) while they are currently using a different one (e.g. magic missiles).

**Comment by TravisGesslein** [comment] 2016-06-07 10:39
Also saving throw is bugged, will be fixed in patch 4

**Comment by TravisGesslein** [comment] 2016-06-07 10:55
Actually... it seems to work perfectly as intended on test maps.
- The skill has a cooldown of 20 seconds, could you have mistaken this for the skill being bugged?
- were the skills in front of the skill priority list? Otherwise there might arise situations where the cooldown of another skill is always finished earlier than the Saving Throws and thus preferred
- Its also relatively costly with 20 rage. This is because it's supposed to be used by tank warriors who don't use their rage for that much else!
- It has a range of 130, which is about the same range that Archer attacks have by default. Hard to measure exactly but in the screenshot it seems like those mobs would be in range... either way I'm going to make the range practically limitless in beta patch 4. Hammers flying across the map taunting targets away!

**Comment by TravisGesslein** [comment] 2016-06-07 11:02
Testing this for a while with the savegame you send me yesterday definitely makes it seem like their rage is often not above 20 (which is no surprise, warriors that are not attacked and have default attack speed generate very little rage). Anyways I increased the range which makes the skill a bunch cooler and it seems to work flawlessly now as long as you have enough rage.

**Closed as completed by TravisGesslein** 2016-06-07 11:02 UTC
Labels: game bug

**Comment by askebv** [comment] 2016-06-07 12:02
@Heishe I didn't include rage in this animation, and I can't confirm if I actively checked since it's a while ago.

Either way, 20 second cooldown still seem useless to me. The stun might be nice, but challenging cry is so much better in the vast majority of scenarios I have encountered.

My logic is this: The primary reason you want targets to hit your tank is so he reduces the damage taken (due to his items) and also make it slightly easier for healers in some narrow situations.

And so, if I don't have challenging cry on, then there's often 2 or more targets that target other raiders. If these targets hit very hard (which is where these skills really matter) then the ability to get just one of them every 20 seconds, doesn't really make any noticeable difference. Neither does the 2 second stun, since the other untaunted targets still hack away at non-tanks.

If I do have challenging cry on, then I'm also very limited in terms of available skills. The main issue with challenging cry is that its cooldown is too high to taunt single targets too. So I need the normal taunt.
That leaves 2 skillbook slots left. Here, I've found Bulwark and Shield Block works best, because Bulwark gives everyone a nice break where they can try to catch up, while dealing with very tough enemies. Sometimes it's even the only time that my other raiders can manage to do anything without dying. But of course it has a super high cooldown.

So the only suitable candidate for replacement is the Shield Block. And the Shield Block gives me 10% damage reduction, more than half the time (because it also cools down between battles, and thus often starts on). This means that all the targets deal roughly 5% less damage, and thus healers save 5% mana. At best, Saving Throw reduces the party damage taken by 50% for 2-3 seconds (because no damage is taken while the enemy is stunned or while the enemy paths to the tank) and then ~25% after that. However, in typical scenarios, like the one above, there's 4+ enemies. And that makes it only a ~6% reduction. But with challenging cry on, the required scenario almost never happens anyway, so you almost only get the occasional stun out of it then. And then you lose the 5% damage reduction.

Maybe I'm wrong, but I just don't see the use.

**Comment by TravisGesslein** [comment] 2016-06-07 12:11
You're right, the cooldown is too restrictive since there's already a decent rage cost to the skill and it overlaps with Challenging Cry too much. I will reduce the cooldown, increase the stun duration, and now that the range is unlimited it has a more specialized use case in certain situations like bigger farm maps as well. What do you think about it?

**Comment by TravisGesslein** [comment] 2016-06-07 12:19
By the way, the original "optimal" use case for Challenging Cry were situations where many monsters spawn on top of your weak archers, mages and priests, like unlucky spawns on farm maps or bosses which spawn monster waves (like Magadom). That's why it has a high cooldown, I specifically didn't want it to be used for all kinds of tauntin jobs a tank might want to do. Now that we reduced the skill slots by 60% I'm not sure if I should do anything about it, I still like the idea of players having to make painful trade-offs :hankey:, especially since it leaves much room open to introduce cool upgrades, set bonuses, unique items, etc. later on which alleviate some of the trade-off troubles that players might feel.

**Comment by askebv** [comment] 2016-06-07 12:22
It'll definitely still not be a good item for any of the current raids, or the arena - because the Challenging Cry already handles every scenario with the Raider Upgrade for it. This is because hard raids are handled slowly, and thus the frequency need of it is reduced. If I'm stomping through the raid too fast, then my other raiders can handle the hits no problem anyway.

But for farm maps, it could be relevant, depending mostly on the cooldown. Because tough farm maps usually crowd you with enemies, and just stunning one enemy just delays things a bit. But having a low cooldown means you can actually save your raiders from being 2-3 hit.

It's a tough thing to balance for sure.

**Comment by TravisGesslein** [comment] 2016-06-07 12:54
I played around a bit and it seems pretty cool, especially with the longer stun duration (5 seconds).

**Comment by TravisGesslein** [comment] 2016-06-07 12:54
I'll put the changes in and see what you guys think when playing around with it.

**Comment by askebv** [comment] 2016-06-07 19:01
@Heishe Trying it out now and it already looks good enough to replace shield block for farming. Now the question is if it's too good :P

**Comment by thorbrian** [comment] 2016-06-08 03:45
FWIW, once I tried out saving throw, I always used it on my two tank warriors, and it's been fantastic, even at 20 rage, 20 cooldown and 2 sec stun. It might be equipment, but my tanks always seem to have 20 rage, and they usually stunning something every 20 seconds (I'm always seeing the green bubbles) and it's drawing targetting off my other characters really well, I find it much more effective than taunt because it's selective on when it's used.

**Comment by thorbrian** [comment] 2016-06-08 03:46
actually what would be really great would be to see cooldowns somehow

**Comment by askebv** [comment] 2016-06-08 05:14
Beta Patch 4 has an option to view cooldowns under "Interface". Perhaps you have a good point about having more than one tank, I haven't tested that out much
