### ISSUE TITLE
Unable to start in chrome (1.0.5): Black screen after loading screen

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#537] opened 2017-03-14 19:11 UTC
I get the same error every time:

![image](https://cloud.githubusercontent.com/assets/4981659/23918170/27bfa99a-08f2-11e7-866e-2fbe148f3a16.png)

Uncaught TypeError: Cannot read property 'setVisible' of undefined

![image](https://cloud.githubusercontent.com/assets/4981659/23918226/6b46d9fe-08f2-11e7-8f27-64d5e400f662.png)

**Comment by askebv** [comment] 2017-03-14 20:25
Was a caching issue. Fixed it by disabling cache while developer console was open:

http://stackoverflow.com/a/7000899/1380710

F12 -> Network -> Disable cache -> Refresh (without closing dev console)

**Comment by TravisGesslein** [comment] 2017-03-15 12:27
Closing this to tunnel everything into issue #545 (since they all probably have the same root cause).

**Closed as completed by TravisGesslein** 2017-03-15 12:27 UTC
