### ISSUE TITLE
[Bug] Vampire drop bug

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#643] opened 2017-08-09 00:46 UTC
On Castle of Undiing vampire drop unkonw item and it generete exception (red message on game).

**Comment by hamburml** [comment] 2017-08-17 12:18
Hello zaqaz123,

thanks for your work and the created issues.
Sadly I am unable to reproduce this error. What browser did you use? Do you have a screenshot of the red message?

Thanks!

**Comment by Talisca** [comment] 2017-08-26 12:42
I think this is related to #653

**Comment by Talisca** [comment] 2017-08-26 12:52
Should be the same issue. The loot of the vampire is alright.

One of its skills got a bug. I will close this issue for now. 

If you got further informations or if you are sure its completly unrelated to the mentioned issue and problem, let us know.

**Closed as completed by Talisca** 2017-08-26 12:52 UTC
Labels: game bug, duplicate
