### ISSUE TITLE
[Bug] Magic dust not incrementing

### ISSUE THREAD

**Issue by hussambutt** [Heishe/idleraiders-second-run#546] opened 2017-03-15 14:35 UTC
I used extract resources on a bunch of items I had saved up. Out of all the items my magic dust is stuck at 1. 

Also when I bought a magic dust offered by the merchant the counter did not go up. My inventory still shows only 1 magic dust. 

I am not sure if any other crafting materials are affected by this bug as this is he first time I have started extracting resources.

**Comment by hussambutt** [comment] 2017-03-15 14:57
I actually have the same issue with Mysterious Stone. When I bought one from the merchant it did not show up in my inventory. I only see one there.

**Comment by TravisGesslein** [comment] 2017-03-15 16:54
Those items can only be extracted from skillbooks, is that the issue maybe? 

But buying it from the merchant should definitely work. Is your name on Kong the same as here? In that case I could pull your save and investigate.

**Comment by TravisGesslein** [comment] 2017-03-15 17:14
Actually it seems there is an issue with extracting items from enchantments at the moment. This can temporarily be fixed by deleting the magic dust and mysterious stone you have, and then avoiding to extract from enchanments until the issue is fixed.

**Comment by TravisGesslein** [comment] 2017-03-24 15:14
This is fixed in the current version of the game.

**Closed as completed by TravisGesslein** 2017-03-24 15:14 UTC
