### ISSUE TITLE
Some warrior bug

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#426] opened 2016-12-31 08:33 UTC
After reaching a certain amount of attack speed, 430 base attack speed to be exact, 2 of my warrior start to have bugs. None of their skills is being triggered anymore (cleave, enrage,hitstreak) this can only be solved by removing items to lower those stats.
Kinda hurt farming speed.
Edit : After futher testing it seems that if the warrior one shot the target with normal hit it doesn't proc any skills, tested on higher hp monster and everything is fine.

**Comment by TravisGesslein** [comment] 2017-01-01 14:48
Thanks for the report. I just want to give a quick update to let you know that we're still on vacation over the holidays, but we're reading all the bug reports that are coming in and will get to work on them as soon as we're back (next week). 

It sounds like the cause of this problem is related to #387 . There are no projectiles involved here, but effectively the target is already dead when the code reaches the point where triggering of other skills happens. A possible solution (to all those trigger skill problems in general) might be to trigger skills anyways, even if the target is already dead... not sure if that breaks anything else, I'll look into it.

**Comment by TravisGesslein** [comment] 2017-01-15 06:28
Is fixed in next patch.

**Closed as completed by TravisGesslein** 2017-01-15 06:28 UTC
Labels: game bug
