### ISSUE TITLE
Game Crash: Winning OneMouth/Seer fight while he does pushing aoe

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#531] opened 2017-03-13 21:42 UTC
[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/839689/error_report.txt)

This was on Chrome 57

**Comment by TravisGesslein** [comment] 2017-03-13 21:49
Thanks, took a quick look at it and it seems to be a harmless crash caused by the code trying to access a property that isn't there anymore because the boss just died. Will be fixed next patch!

**Closed as completed by TravisGesslein** 2017-03-13 21:49 UTC
Labels: game bug
