### ISSUE TITLE
Hp values missing from some bosses

### ISSUE THREAD

**Issue by Syntastic** [Heishe/idleraiders-second-run#370] opened 2016-10-31 22:31 UTC
![screenshot_17](https://cloud.githubusercontent.com/assets/6775313/19873946/cea3ab02-9f8f-11e6-8f29-848d57c43c65.png)

**Comment by dcish** [comment] 2016-11-01 10:49
I've had this bug as well, a refresh of client usually fixes it but probably shouldn't happen

**Comment by TravisGesslein** [comment] 2016-11-02 09:52
By any chance,  do you know of a way to reliably reproduce this issue? The problem has existed for some while, but we've been unable to track it down so far, as it seems to happen relatively rarely.

**Comment by TravisGesslein** [comment] 2017-02-05 22:39
Closing for now, since it doesn't seem to happen anymore. Either way, I'm sure there will be new issues opened for this when it happens again.

**Closed as completed by TravisGesslein** 2017-02-05 22:39 UTC
