### ISSUE TITLE
Can't open loot chests

### ISSUE THREAD

**Issue by musaii** [Heishe/idleraiders-second-run#628] opened 2017-07-30 02:40 UTC
Get this error when I open loot chests in 1.1: Cannot read property 'rare' of undefined, status: 400
![loot chest](https://user-images.githubusercontent.com/20647711/28750153-f96ada32-74ae-11e7-9576-7f600e4ad95e.PNG)

**Comment by hamburml** [comment] 2017-08-06 11:37
Does this still happen when you reload the page with clearing/ignoring the cache?

**Comment by musaii** [comment] 2017-08-06 14:36
just cleared cache + reloaded.  Still happens

**Comment by hamburml** [comment] 2017-08-06 16:38
Is your username on kongregate also musaii? Did you bought the loot chest before 1.1 or after 1.1?

**Comment by musaii** [comment] 2017-08-06 22:38
no it's holybatman.  I bought the chests after 1.1

**Comment by hamburml** [comment] 2017-08-06 23:34
Did you clicked the 'Open all' button or did you clicked on the loot chest directly?

**Comment by musaii** [comment] 2017-08-07 00:46
Opening one doesn't work, if I click on one check it does nothing.  If I click open all I get the error.

**Comment by hamburml** [comment] 2017-08-07 11:15
What browser do you use? 64 bit or 32 bit? 
I try to find the cause of the error. I just looked at your account and found out that two chests weren't opened yet. I also looked at your savegame and I can see all chests and the two unopened ones.
I am sorry this is happening.

**Comment by musaii** [comment] 2017-08-07 14:07
64 bit chrome, just updated too:
Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by 13CI13** [comment] 2017-08-08 13:44
I have this error too. It happens when i try to open the chests at tier 9 & 10. 
2 of my loot chests worked at tier 1 when i accidentally tried to see if the issue was fixed after a wisdom reset, though that left me with tier 1-3 loot which isnt much use ^^

**Comment by 13CI13** [comment] 2017-08-10 10:44
Seems to be fixed now, thanks!

**Comment by musaii** [comment] 2017-08-10 11:48
Yup, same.

**Closed as completed** 2017-08-12 04:49 UTC
