### ISSUE TITLE
Sometimes buildings briefly turn transparent with a green tint

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#208] opened 2016-06-08 18:24 UTC
It happens to all buildings at once, as far as I've seen.

I've seen this happen several times since beta patch 1 or so, but haven't been able to screenshot it, since it usually goes away after 1-4 seconds. I don't know if it's something intentional that I don't understand, or if it's just a small visual glitch.

I've also tried reproducing it, but obviously haven't had much luck.

I'll try to take a screenshot of it if I can though - unless someone else beats me to it.

**Comment by Talisca** [comment] 2016-06-09 05:26
The last time I've seen this bug was about one month ago. I am sure its related to some Healing Skillbooks, but I can't reproduce this behavior anymore.

**Comment by askebv** [comment] 2016-06-09 06:56
Yeah I've noticed my healers are always healing a ton when it happens. The two scenarios I've seen it happen frequently are 1) when I've just exited building mode, having built or deleted structures and 2) when I'm in a menu, having just dragged and dropped stuff in the priority list, or read tooltips of items in the trades of sholar's tower or the market.

I don't know if those things are related though. The easiest way to get my healers go crazy are when I'm at a super high farm level - and thus die all the time - but it still only happens every once in a while. There can easily be hours without it happening.

I'm using rejuvenation, propagation and healstreak, by the way.

**Comment by TravisGesslein** [comment] 2016-06-09 09:05
The last time this happened was because of the AOE heal particle effect. Maybe propagation is still bugged, I'll check it out.

**Comment by TravisGesslein** [comment] 2016-06-09 09:45
A couple of particle effects were missing their correct textures (fixed now). I couldn't reproduce the bug before but I  don't know what else could trigger it. I'll close this and reopen if it happens again after Patch 5.

**Comment by askebv** [comment] 2016-06-09 18:06
@Heishe I just had it happen again. Could it be when the propagation effect is triggered on a farm map, while the raider is dying, while viewing the base?

I managed to capture it, and there's a propagation effect in the bottom - but no priest there:

![image](https://cloud.githubusercontent.com/assets/4981659/15942331/39d2daec-2e84-11e6-8f0e-ef8ce71fd3e9.png)

**Comment by askebv** [comment] 2016-06-12 09:34
@Heishe I know you love when issues are closed - but unless you fixed this one, perhaps it should be reopened?

**Comment by TravisGesslein** [comment] 2016-06-12 09:35
Yeah, it happened to me today too. Will look into it.

**Comment by TravisGesslein** [comment] 2016-06-12 09:44
Yes that does indeed seem to be the cause of the effect. Why though, I have no idea O_O

**Comment by askebv** [comment] 2016-06-12 09:48
@Heishe You don't think it's related to casting a spell while in limbo? I've noticed spells aren't often interrupted if the caster or enemy dies between the initial mana consumption and the end of the casting animation. I don't know your code of course, but I would guess there could be some odd undesired effects if the target or caster isn't located in the map that your expected behavior calls for.

**Comment by TravisGesslein** [comment] 2016-06-12 11:21
Oh, I know why it happens (it happens right when a raider dies who currently has that effect active on themself), I just don't know why the stuff ends up being green all over the place. I will fix it eventually :D

**Closed as completed** 2017-02-14 08:59 UTC
Labels: game bug
