### ISSUE TITLE
Bug with dps warrior w obsidian claymore

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#369] opened 2016-10-31 15:52 UTC
Since last patch my dps warrior has attempted to pull the second boss early.  This only happens while the unit is wielding obsidian claymore as far as i can tell.

**Comment by TravisGesslein** [comment] 2016-10-31 17:31
Hi, which raid do you mean? Could you send us the savegame where this happens to social **at** pitforest.de?

I'm assuming you mean that the Warrior just runs to the second boss for some reason?

**Comment by dcish** [comment] 2016-10-31 17:55
Yeah. It happened in undead castle he ran to werewolf. Then again it happened in golem area where he ran from first to second boss. It stopped when I unequipped the item. Where is save located.

**Comment by TravisGesslein** [comment] 2016-11-21 14:25
This seems to have been caused by the Disarm skillbook. The boss already has it applied so the raider wanders on over to the second to apply it to that one, too. This and similar behavior for the Crippling Shot will be fixed in Patch 16.

(Thanks Thorbrian)

**Closed as completed by TravisGesslein** 2016-11-21 14:25 UTC
Labels: game bug
