### ISSUE TITLE
Inn is 2x1 instead of 2x2 when placing it

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#13] opened 2016-06-01 20:29 UTC
It seems to be possible to build the inn on top of other buildings:

![image](https://cloud.githubusercontent.com/assets/4981659/15724644/48d3cfde-2848-11e6-92dd-11d99d03f521.png)

Also on the top, where it sticks out of the map.

**Comment by TravisGesslein** [comment] 2016-06-01 21:05
The first case is intentional, we figured some buildings take up too much space otherwise, and leaving a "1 tile" deep layer where we allow overlapping with larger buildings is supposed to fake some kind of 3D perspective. I think we may need to adjust the art here, the inn looks a bit too large. 

The second case (building at the top) shouldn't be allowed though. Will be fixed!

**Comment by TravisGesslein** [comment] 2016-06-02 10:35
Also related: #34

**Comment by TravisGesslein** [comment] 2016-06-02 11:34
@Muskar Do you mean you can build the building in the very top row of the map and half of the building then sticks out into nothingness? I can't reproduce it.

**Comment by askebv** [comment] 2016-06-02 12:48
@Heishe I thought so, but I think it was just the edge of the camera. I can't reproduce it either.

**Comment by TravisGesslein** [comment] 2016-06-02 12:59
Good, one bug less! :D

**Closed as completed by TravisGesslein** 2016-06-02 12:59 UTC
Labels: game bug
