### ISSUE TITLE
Well buff doesn't match well description

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#123] opened 2016-06-04 20:13 UTC
The Well description says it's a 3% energy regeneration buff for all raiders

However, the well buff says it's a +2% additive rage generation for warriors

**Comment by askebv** [comment] 2016-06-04 21:34
[#90](https://github.com/Heishe/idleraiders-second-run/issues/90#issuecomment-223620535)

**Comment by askebv** [comment] 2016-06-07 16:11
@thorbrian can you close this issue. This is a duplicate of the solved issue that I referred to.

**Closed as completed** 2016-06-08 03:28 UTC
